"""empty message

Revision ID: b609da6b0dd6
Revises: 
Create Date: 2024-11-02 14:38:46.524356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b609da6b0dd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('isin', sa.String(length=50), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('series', sa.String(length=50), nullable=True),
    sa.Column('trade_type', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('trade_id', sa.String(length=50), nullable=True),
    sa.Column('order_execution_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('users')
    # ### end Alembic commands ###
